train: /mnt/c/Datasets/Mitotic Figures/MIDOG2021/YoloV7-Dataset/images/train
val: /mnt/c/Datasets/Mitotic Figures/MIDOG2021/YoloV7-Dataset/images/val
test: /mnt/c/Datasets/Mitotic Figures/MIDOG2021/YoloV7-Dataset/images/test

# Classes
nc: 1  # number of classes
names: ['Mitotic figure']  # class names